//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/2/2020 17:22:21
namespace WPFTestApp.Models
{
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    public partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Person> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CountryCodeNavigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.CountrySingle CountryCodeNavigation
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CountryCodeNavigation == null))
                {
                    this._CountryCodeNavigation = new global::WPFTestApp.Models.CountrySingle(this.Context, GetPath("CountryCodeNavigation"));
                }
                return this._CountryCodeNavigation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.CountrySingle _CountryCodeNavigation;
        /// <summary>
        /// There are no comments for Greeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.GreetingSingle Greeting
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Greeting == null))
                {
                    this._Greeting = new global::WPFTestApp.Models.GreetingSingle(this.Context, GetPath("Greeting"));
                }
                return this._Greeting;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.GreetingSingle _Greeting;
        /// <summary>
        /// There are no comments for PersonContact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> PersonContact
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PersonContact == null))
                {
                    this._PersonContact = Context.CreateQuery<global::WPFTestApp.Models.PersonContact>(GetPath("PersonContact"));
                }
                return this._PersonContact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> _PersonContact;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Person : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="genderId">Initial value of GenderId.</param>
        /// <param name="firstContact">Initial value of FirstContact.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Person CreatePerson(int ID, byte genderId, global::System.DateTimeOffset firstContact)
        {
            Person person = new Person();
            person.Id = ID;
            person.GenderId = genderId;
            person.FirstContact = firstContact;
            return person;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Fname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Fname
        {
            get
            {
                return this._Fname;
            }
            set
            {
                this.OnFnameChanging(value);
                this._Fname = value;
                this.OnFnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Fname;
        partial void OnFnameChanging(string value);
        partial void OnFnameChanged();
        /// <summary>
        /// There are no comments for Property Lname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Lname
        {
            get
            {
                return this._Lname;
            }
            set
            {
                this.OnLnameChanging(value);
                this._Lname = value;
                this.OnLnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Lname;
        partial void OnLnameChanging(string value);
        partial void OnLnameChanged();
        /// <summary>
        /// There are no comments for Property Cpny in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Cpny
        {
            get
            {
                return this._Cpny;
            }
            set
            {
                this.OnCpnyChanging(value);
                this._Cpny = value;
                this.OnCpnyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Cpny;
        partial void OnCpnyChanging(string value);
        partial void OnCpnyChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property CountryCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string CountryCode
        {
            get
            {
                return this._CountryCode;
            }
            set
            {
                this.OnCountryCodeChanging(value);
                this._CountryCode = value;
                this.OnCountryCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CountryCode;
        partial void OnCountryCodeChanging(string value);
        partial void OnCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                this._Zip = value;
                this.OnZipChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property GenderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte GenderId
        {
            get
            {
                return this._GenderId;
            }
            set
            {
                this.OnGenderIdChanging(value);
                this._GenderId = value;
                this.OnGenderIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _GenderId;
        partial void OnGenderIdChanging(byte value);
        partial void OnGenderIdChanged();
        /// <summary>
        /// There are no comments for Property GreetingId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> GreetingId
        {
            get
            {
                return this._GreetingId;
            }
            set
            {
                this.OnGreetingIdChanging(value);
                this._GreetingId = value;
                this.OnGreetingIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _GreetingId;
        partial void OnGreetingIdChanging(global::System.Nullable<int> value);
        partial void OnGreetingIdChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property FirstContact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset FirstContact
        {
            get
            {
                return this._FirstContact;
            }
            set
            {
                this.OnFirstContactChanging(value);
                this._FirstContact = value;
                this.OnFirstContactChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _FirstContact;
        partial void OnFirstContactChanging(global::System.DateTimeOffset value);
        partial void OnFirstContactChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property CountryCodeNavigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.Country CountryCodeNavigation
        {
            get
            {
                return this._CountryCodeNavigation;
            }
            set
            {
                this.OnCountryCodeNavigationChanging(value);
                this._CountryCodeNavigation = value;
                this.OnCountryCodeNavigationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.Country _CountryCodeNavigation;
        partial void OnCountryCodeNavigationChanging(global::WPFTestApp.Models.Country value);
        partial void OnCountryCodeNavigationChanged();
        /// <summary>
        /// There are no comments for Property Greeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.Greeting Greeting
        {
            get
            {
                return this._Greeting;
            }
            set
            {
                this.OnGreetingChanging(value);
                this._Greeting = value;
                this.OnGreetingChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.Greeting _Greeting;
        partial void OnGreetingChanging(global::WPFTestApp.Models.Greeting value);
        partial void OnGreetingChanged();
        /// <summary>
        /// There are no comments for Property PersonContact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.PersonContact> PersonContact
        {
            get
            {
                return this._PersonContact;
            }
            set
            {
                this.OnPersonContactChanging(value);
                this._PersonContact = value;
                this.OnPersonContactChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.PersonContact> _PersonContact = new global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.PersonContact>();
        partial void OnPersonContactChanging(global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.PersonContact> value);
        partial void OnPersonContactChanged();
    }
    /// <summary>
    /// There are no comments for PersonContactSingle in the schema.
    /// </summary>
    public partial class PersonContactSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PersonContact>
    {
        /// <summary>
        /// Initialize a new PersonContactSingle object.
        /// </summary>
        public PersonContactSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonContactSingle object.
        /// </summary>
        public PersonContactSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonContactSingle object.
        /// </summary>
        public PersonContactSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PersonContact> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.PersonSingle Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = new global::WPFTestApp.Models.PersonSingle(this.Context, GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.PersonSingle _Person;
    }
    /// <summary>
    /// There are no comments for PersonContact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonContactId
    /// PersonId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonContactId", "PersonId")]
    public partial class PersonContact : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new PersonContact object.
        /// </summary>
        /// <param name="personContactId">Initial value of PersonContactId.</param>
        /// <param name="contactTypeId">Initial value of ContactTypeId.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PersonContact CreatePersonContact(int personContactId, int contactTypeId, byte active)
        {
            PersonContact personContact = new PersonContact();
            personContact.PersonContactId = personContactId;
            personContact.ContactTypeId = contactTypeId;
            personContact.Active = active;
            return personContact;
        }
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _PersonId;
        partial void OnPersonIdChanging(global::System.Nullable<int> value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property PersonContactId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int PersonContactId
        {
            get
            {
                return this._PersonContactId;
            }
            set
            {
                this.OnPersonContactIdChanging(value);
                this._PersonContactId = value;
                this.OnPersonContactIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _PersonContactId;
        partial void OnPersonContactIdChanging(int value);
        partial void OnPersonContactIdChanged();
        /// <summary>
        /// There are no comments for Property ContactTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ContactTypeId
        {
            get
            {
                return this._ContactTypeId;
            }
            set
            {
                this.OnContactTypeIdChanging(value);
                this._ContactTypeId = value;
                this.OnContactTypeIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ContactTypeId;
        partial void OnContactTypeIdChanging(int value);
        partial void OnContactTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Txt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt
        {
            get
            {
                return this._Txt;
            }
            set
            {
                this.OnTxtChanging(value);
                this._Txt = value;
                this.OnTxtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt;
        partial void OnTxtChanging(string value);
        partial void OnTxtChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Active;
        partial void OnActiveChanging(byte value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::WPFTestApp.Models.Person Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::WPFTestApp.Models.Person _Person;
        partial void OnPersonChanging(global::WPFTestApp.Models.Person value);
        partial void OnPersonChanged();
    }
    /// <summary>
    /// There are no comments for GreetingSingle in the schema.
    /// </summary>
    public partial class GreetingSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Greeting>
    {
        /// <summary>
        /// Initialize a new GreetingSingle object.
        /// </summary>
        public GreetingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new GreetingSingle object.
        /// </summary>
        public GreetingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new GreetingSingle object.
        /// </summary>
        public GreetingSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Greeting> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = Context.CreateQuery<global::WPFTestApp.Models.Person>(GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> _Person;
    }
    /// <summary>
    /// There are no comments for Greeting in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Greeting : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Greeting object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Greeting CreateGreeting(int ID, byte active)
        {
            Greeting greeting = new Greeting();
            greeting.Id = ID;
            greeting.Active = active;
            return greeting;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Txt1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt1
        {
            get
            {
                return this._Txt1;
            }
            set
            {
                this.OnTxt1Changing(value);
                this._Txt1 = value;
                this.OnTxt1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt1;
        partial void OnTxt1Changing(string value);
        partial void OnTxt1Changed();
        /// <summary>
        /// There are no comments for Property Txt2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt2
        {
            get
            {
                return this._Txt2;
            }
            set
            {
                this.OnTxt2Changing(value);
                this._Txt2 = value;
                this.OnTxt2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt2;
        partial void OnTxt2Changing(string value);
        partial void OnTxt2Changed();
        /// <summary>
        /// There are no comments for Property Txt3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt3
        {
            get
            {
                return this._Txt3;
            }
            set
            {
                this.OnTxt3Changing(value);
                this._Txt3 = value;
                this.OnTxt3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt3;
        partial void OnTxt3Changing(string value);
        partial void OnTxt3Changed();
        /// <summary>
        /// There are no comments for Property Txt4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt4
        {
            get
            {
                return this._Txt4;
            }
            set
            {
                this.OnTxt4Changing(value);
                this._Txt4 = value;
                this.OnTxt4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt4;
        partial void OnTxt4Changing(string value);
        partial void OnTxt4Changed();
        /// <summary>
        /// There are no comments for Property TxtLetter1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TxtLetter1
        {
            get
            {
                return this._TxtLetter1;
            }
            set
            {
                this.OnTxtLetter1Changing(value);
                this._TxtLetter1 = value;
                this.OnTxtLetter1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TxtLetter1;
        partial void OnTxtLetter1Changing(string value);
        partial void OnTxtLetter1Changed();
        /// <summary>
        /// There are no comments for Property TxtLetter2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TxtLetter2
        {
            get
            {
                return this._TxtLetter2;
            }
            set
            {
                this.OnTxtLetter2Changing(value);
                this._TxtLetter2 = value;
                this.OnTxtLetter2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TxtLetter2;
        partial void OnTxtLetter2Changing(string value);
        partial void OnTxtLetter2Changed();
        /// <summary>
        /// There are no comments for Property TxtLetter3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TxtLetter3
        {
            get
            {
                return this._TxtLetter3;
            }
            set
            {
                this.OnTxtLetter3Changing(value);
                this._TxtLetter3 = value;
                this.OnTxtLetter3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TxtLetter3;
        partial void OnTxtLetter3Changing(string value);
        partial void OnTxtLetter3Changed();
        /// <summary>
        /// There are no comments for Property TxtLetter4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TxtLetter4
        {
            get
            {
                return this._TxtLetter4;
            }
            set
            {
                this.OnTxtLetter4Changing(value);
                this._TxtLetter4 = value;
                this.OnTxtLetter4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TxtLetter4;
        partial void OnTxtLetter4Changing(string value);
        partial void OnTxtLetter4Changed();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Active;
        partial void OnActiveChanging(byte value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> _Person = new global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person>();
        partial void OnPersonChanging(global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> value);
        partial void OnPersonChanged();
    }
    /// <summary>
    /// There are no comments for CountrySingle in the schema.
    /// </summary>
    public partial class CountrySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Country>
    {
        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Country> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = Context.CreateQuery<global::WPFTestApp.Models.Person>(GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> _Person;
    }
    /// <summary>
    /// There are no comments for Country in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Code
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Code")]
    public partial class Country : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="addrFormatId">Initial value of AddrFormatId.</param>
        /// <param name="isVatIncluded">Initial value of IsVatIncluded.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Country CreateCountry(string code, byte addrFormatId, byte isVatIncluded, byte active)
        {
            Country country = new Country();
            country.Code = code;
            country.AddrFormatId = addrFormatId;
            country.IsVatIncluded = isVatIncluded;
            country.Active = active;
            return country;
        }
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Txt1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt1
        {
            get
            {
                return this._Txt1;
            }
            set
            {
                this.OnTxt1Changing(value);
                this._Txt1 = value;
                this.OnTxt1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt1;
        partial void OnTxt1Changing(string value);
        partial void OnTxt1Changed();
        /// <summary>
        /// There are no comments for Property Txt2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt2
        {
            get
            {
                return this._Txt2;
            }
            set
            {
                this.OnTxt2Changing(value);
                this._Txt2 = value;
                this.OnTxt2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt2;
        partial void OnTxt2Changing(string value);
        partial void OnTxt2Changed();
        /// <summary>
        /// There are no comments for Property Txt3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt3
        {
            get
            {
                return this._Txt3;
            }
            set
            {
                this.OnTxt3Changing(value);
                this._Txt3 = value;
                this.OnTxt3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt3;
        partial void OnTxt3Changing(string value);
        partial void OnTxt3Changed();
        /// <summary>
        /// There are no comments for Property Txt4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Txt4
        {
            get
            {
                return this._Txt4;
            }
            set
            {
                this.OnTxt4Changing(value);
                this._Txt4 = value;
                this.OnTxt4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Txt4;
        partial void OnTxt4Changing(string value);
        partial void OnTxt4Changed();
        /// <summary>
        /// There are no comments for Property IntDialCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string IntDialCode
        {
            get
            {
                return this._IntDialCode;
            }
            set
            {
                this.OnIntDialCodeChanging(value);
                this._IntDialCode = value;
                this.OnIntDialCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _IntDialCode;
        partial void OnIntDialCodeChanging(string value);
        partial void OnIntDialCodeChanged();
        /// <summary>
        /// There are no comments for Property AddrFormatId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte AddrFormatId
        {
            get
            {
                return this._AddrFormatId;
            }
            set
            {
                this.OnAddrFormatIdChanging(value);
                this._AddrFormatId = value;
                this.OnAddrFormatIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _AddrFormatId;
        partial void OnAddrFormatIdChanging(byte value);
        partial void OnAddrFormatIdChanged();
        /// <summary>
        /// There are no comments for Property IsVatIncluded in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte IsVatIncluded
        {
            get
            {
                return this._IsVatIncluded;
            }
            set
            {
                this.OnIsVatIncludedChanging(value);
                this._IsVatIncluded = value;
                this.OnIsVatIncludedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _IsVatIncluded;
        partial void OnIsVatIncludedChanging(byte value);
        partial void OnIsVatIncludedChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual byte Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Active;
        partial void OnActiveChanging(byte value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> _Person = new global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person>();
        partial void OnPersonChanging(global::System.Collections.ObjectModel.Collection<global::WPFTestApp.Models.Person> value);
        partial void OnPersonChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Person as global::WPFTestApp.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WPFTestApp.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::WPFTestApp.Models.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Person as global::WPFTestApp.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::WPFTestApp.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::WPFTestApp.Models.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.PersonContact as global::WPFTestApp.Models.PersonContactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WPFTestApp.Models.PersonContactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::WPFTestApp.Models.PersonContactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.PersonContact as global::WPFTestApp.Models.PersonContactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="personContactId">The value of personContactId</param>
        /// <param name="personId">The value of personId</param>
        public static global::WPFTestApp.Models.PersonContactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> source,
            int personContactId, 
            global::System.Nullable<int> personId)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PersonContactId", personContactId }, 
                { "PersonId", personId }
            };
            return new global::WPFTestApp.Models.PersonContactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Greeting as global::WPFTestApp.Models.GreetingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WPFTestApp.Models.GreetingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Greeting> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::WPFTestApp.Models.GreetingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Greeting as global::WPFTestApp.Models.GreetingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::WPFTestApp.Models.GreetingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Greeting> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::WPFTestApp.Models.GreetingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Country as global::WPFTestApp.Models.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WPFTestApp.Models.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Country> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::WPFTestApp.Models.CountrySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WPFTestApp.Models.Country as global::WPFTestApp.Models.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="code">The value of code</param>
        public static global::WPFTestApp.Models.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Country> source,
            string code)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Code", code }
            };
            return new global::WPFTestApp.Models.CountrySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> Person
        {
            get
            {
                if ((this._Person == null))
                {
                    this._Person = base.CreateQuery<global::WPFTestApp.Models.Person>("Person");
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Person> _Person;
        /// <summary>
        /// There are no comments for PersonContact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> PersonContact
        {
            get
            {
                if ((this._PersonContact == null))
                {
                    this._PersonContact = base.CreateQuery<global::WPFTestApp.Models.PersonContact>("PersonContact");
                }
                return this._PersonContact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.PersonContact> _PersonContact;
        /// <summary>
        /// There are no comments for Greeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Greeting> Greeting
        {
            get
            {
                if ((this._Greeting == null))
                {
                    this._Greeting = base.CreateQuery<global::WPFTestApp.Models.Greeting>("Greeting");
                }
                return this._Greeting;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Greeting> _Greeting;
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Country> Country
        {
            get
            {
                if ((this._Country == null))
                {
                    this._Country = base.CreateQuery<global::WPFTestApp.Models.Country>("Country");
                }
                return this._Country;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WPFTestApp.Models.Country> _Country;
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToPerson(global::WPFTestApp.Models.Person person)
        {
            base.AddObject("Person", person);
        }
        /// <summary>
        /// There are no comments for PersonContact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToPersonContact(global::WPFTestApp.Models.PersonContact personContact)
        {
            base.AddObject("PersonContact", personContact);
        }
        /// <summary>
        /// There are no comments for Greeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToGreeting(global::WPFTestApp.Models.Greeting greeting)
        {
            base.AddObject("Greeting", greeting);
        }
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCountry(global::WPFTestApp.Models.Country country)
        {
            base.AddObject("Country", country);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ODataServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
